Repository Azure/azure-cosmos-js, pull requests merged in 2018-07, with the labels that each got.

#30 Enable Travis CI
  travis.yml
Labels: engineering

#52 Feature/#40 2
  .vscode/settings.json
  README.md
  src/client/Conflict/Conflict.ts
  src/client/Conflict/ConflictResponse.ts
  src/client/Conflict/index.ts
  src/client/Offer/Offer.ts
  src/client/Offer/OfferResponse.ts
  src/client/Offer/Offers.ts
  src/client/Offer/index.ts
  src/client/Permission/Permission.ts
  src/client/Permission/PermissionResponse.ts
  src/client/Permission/Permissions.ts
  src/client/Permission/index.ts
  src/client/StoredProcedure/StoredProcedure.ts
  src/client/StoredProcedure/StoredProcedureResponse.ts
  src/client/StoredProcedure/StoredProcedures.ts
  src/client/Trigger/Trigger.ts
  src/client/Trigger/TriggerResponse.ts
  src/client/Trigger/Triggers.ts
  src/client/Trigger/index.ts
  src/client/User/User.ts
  src/client/User/UserResponse.ts
  src/client/User/Users.ts
  src/client/User/index.ts
  src/client/UserDefinedFunction/UserDefinedFunction.ts
  src/client/UserDefinedFunction/UserDefinedFunctionResponse.ts
  src/client/UserDefinedFunction/UserDefinedFunctions.ts
  src/client/UserDefinedFunction/index.ts
  src/test/common/TestHelpers.ts
  src/test/functional/authorization.spec.ts
  src/test/functional/permission.spec.ts
  src/test/functional/sproc.spec.ts
  src/test/functional/trigger.spec.ts
  src/test/functional/udf.spec.ts
  src/test/functional/user.spec.ts
  src/test/integration/authorization.spec.ts
Labels: breaking, feature

#64 Refactor Tests to use Test Helpers
  src/test/common/BaselineTest.PathParser.ts
  src/test/common/TestHelpers.ts
  src/test/common/_testConfig.ts
  src/test/functional/HashPartitionResolver.spec.ts
  src/test/functional/authorization.spec.ts
  src/test/functional/client.spec.ts
  src/test/functional/container.spec.ts
  src/test/functional/database.spec.ts
  src/test/functional/databaseaccount.spec.ts
  src/test/functional/item.spec.ts
  src/test/functional/offer.spec.ts.ignore
  src/test/functional/permission.spec.ts
  src/test/functional/query.spec.ts
  src/test/functional/spatial.spec.ts
  src/test/functional/sproc.spec.ts
  src/test/functional/trigger.spec.ts
  src/test/functional/ttl.spec.ts
  src/test/functional/udf.spec.ts
  src/test/functional/user.spec.ts
  src/test/integration/aggregateQuery.spec.ts
  src/test/integration/authorization.spec.ts
  src/test/integration/crossPartition.spec.ts
  src/test/integration/documentClient.spec.ts
  src/test/integration/encoding.spec.ts
  src/test/integration/incrementalFeed.spec.ts
  src/test/integration/proxy.spec.ts
  src/test/integration/query.spec.ts
  src/test/integration/queryMetrics.spec.ts
  src/test/integration/retry.spec.ts
  src/test/integration/ruPerMin.spec.ts
  src/test/integration/session.spec.ts
  src/test/integration/split.spec.ts
  src/test/integration/sslVerification.spec.ts
  src/test/unit/sessionContainer.spec.ts
Labels: engineering

#66 CreateIfNotExists (#35)
  src/client/Container/Containers.ts
  src/client/Database/Databases.ts
  src/test/common/TestHelpers.ts
  src/test/functional/container.spec.ts
  src/test/functional/database.spec.ts
Labels: feature

#69 Update config to preserve comments
  tsconfig.json
Labels: bug, documentation

#79 Update samples to new OM
  .vscode/launch.json
  README.md
  samples/ContainerManagement/app.js
  samples/ContainerManagement/package.json
  samples/DatabaseManagement/app.js
  samples/DatabaseManagement/package.json
  samples/DocumentManagement/app.js
  samples/IndexManagement/app.js
  samples/IndexManagement/package.json
  samples/ItemManagement/app.js
  samples/ItemManagement/package.json
  samples/Partitioning/README.md
  samples/Partitioning/app.js
  samples/Partitioning/package.json
  samples/ServerSideScripts/app.js
  samples/ServerSideScripts/package.json
  samples/Shared/config.js
  samples/Shared/utils.js
  samples/TodoApp/app.js
  samples/TodoApp/config.js
  samples/TodoApp/models/CosmosUtils.js
  samples/TodoApp/models/taskDao.js
  samples/UserManagement/app.js
  samples/UserManagement/package.json
  samples/readme.md
Labels: documentation

#85 Update the exported types
  src/index.ts
  src/test/functional/HashPartitionResolver.spec.ts
  src/test/integration/authorization.spec.ts
  src/test/integration/proxy.spec.ts
  src/test/integration/session.spec.ts
  src/test/unit/base.spec.ts
  src/test/unit/range.spec.ts
  src/test/unit/rangePartitionResolver.spec.ts
Labels: breaking, improvement

#86 Change all string enum properties to keyof typof enum properties
  samples/IndexManagement/app.js
  src/CosmosClient.ts
  src/CosmosClientOptions.ts
  src/documents/ConnectionPolicy.ts
  src/documents/IndexingMode.ts
  src/documents/IndexingPolicy.ts
  src/documents/PartitionKeyDefinition.ts
  src/test/functional/container.spec.ts
  src/test/integration/encoding.spec.ts
Labels: improvement

#87 Update forEach/Adds AsyncIterator
  src/queryIterator.ts
  src/test/functional/query.spec.ts
  src/test/integration/aggregateQuery.spec.ts
  src/test/integration/crossPartition.spec.ts
Labels: breaking, feature

#89 TypeScript 3.0 and other random package updates
  .vscode/launch.json
  package-lock.json
  package.json
Labels: engineering
