Repository Azure/azure-cosmos-js, pull requests merged in 2018-09, with the labels that each got.

#114 Remove sourcemap from the bundle in webpack -p mode. Helps #61
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.prod.json
  webpack.config.js
Labels: community, engineering

#131 Update karma to 3.0.0
  package-lock.json
  package.json
Labels: engineering

#130 Fix/mrw fixes
  samples/MultiRegionWrite/ConflictWorker.ts
  src/ClientContext.ts
  src/LocationCache.ts
  src/LocationInfo.ts
  src/globalEndpointManager.ts
  src/request/LocationRouting.ts
  src/request/RequestContext.ts
  src/retry/IRetryPolicy.ts
  src/retry/RetryContext.ts
  src/retry/endpointDiscoveryRetryPolicy.ts
  src/retry/index.ts
  src/retry/retryUtility.ts
  src/retry/sessionReadRetryPolicy.ts
  src/retry/sessionRetryPolicy.ts
  src/test/unit/locationCache.spec.ts
Labels: improvement

#135 buffer updates & connection policy fixes
  src/ClientContext.ts
  src/CosmosClient.ts
  src/CosmosClientOptions.ts
  src/auth.ts
  src/common/helper.ts
  src/common/platform.ts
  src/common/resourceId.ts
  src/documents/ConnectionPolicy.ts
  src/request/RequestHandler.ts
  src/test/functional/client.spec.ts
Labels: improvement

#133 Update response types
  src/ClientContext.ts
  src/client/Conflict/Conflict.ts
  src/client/Conflict/ConflictResponse.ts
  src/client/Conflict/Conflicts.ts
  src/client/Container/Container.ts
  src/client/Container/ContainerResponse.ts
  src/client/Container/Containers.ts
  src/client/Database/Database.ts
  src/client/Database/DatabaseResponse.ts
  src/client/Database/Databases.ts
  src/client/Item/Item.ts
  src/client/Item/ItemResponse.ts
  src/client/Item/Items.ts
  src/client/Offer/Offer.ts
  src/client/Offer/OfferResponse.ts
  src/client/Offer/Offers.ts
  src/client/Permission/Permission.ts
  src/client/Permission/PermissionBody.ts
  src/client/Permission/PermissionResponse.ts
  src/client/Permission/Permissions.ts
  src/client/Resource.ts
  src/client/StoredProcedure/StoredProcedure.ts
  src/client/StoredProcedure/StoredProcedureResponse.ts
  src/client/StoredProcedure/StoredProcedures.ts
  src/client/Trigger/Trigger.ts
  src/client/Trigger/TriggerResponse.ts
  src/client/Trigger/Triggers.ts
  src/client/User/User.ts
  src/client/User/UserResponse.ts
  src/client/User/Users.ts
  src/client/UserDefinedFunction/UserDefinedFunction.ts
  src/client/UserDefinedFunction/UserDefinedFunctionResponse.ts
  src/client/UserDefinedFunction/UserDefinedFunctions.ts
  src/client/index.ts
  src/test/common/TestHelpers.ts
  src/test/functional/item.spec.ts
Labels: breaking, improvement

#134 Roll version to 2.0.0
  changelog.md
  package.json
  src/common/constants.ts
  src/test/unit/plaftorm.spec.ts
Labels: engineering

#142 Retry interface implementation must exactly match
  src/retry/endpointDiscoveryRetryPolicy.ts
  src/retry/sessionRetryPolicy.ts
Labels: patch
