Repository Azure/azure-cosmos-js, pull requests merged in 2018-10, with the labels that each got.

#162 typo: teh -> the
  src/client/Database/Databases.ts
  src/common/helper.ts
  src/globalEndpointManager.ts
  src/queryExecutionContext/SqlQuerySpec.ts
Labels: documentation

#161 Remove lib from tsconfig. Use reference directive for AsyncIterable
  package-lock.json
  package.json
  src/queryIterator.ts
  tsconfig.json
Labels: improvement

#165 chore: Match EditorConfig match Prettier TS file rule
  .editorConfig
Labels: engineering

#166 Remove big integer
  package-lock.json
  package.json
  src/common/index.ts
  src/common/resourceId.ts
  src/session/VectorSessionToken.ts
  src/session/sessionContainer.ts
  src/test/unit/ResourceId.spec.ts
Labels: improvement

#168 Add build badges
  README.md
Labels: documentation
