Repository Azure/azure-cosmos-js, pull requests merged in 2019-04, with the labels that each got.

#288 Upgrade to typescript 3.4. Close #274
  package-lock.json
  package.json
Labels: v3

#289 Fix Request Charge Aggregation
  package.json
  src/client/Item/Items.ts
  src/queryExecutionContext/EndpointComponent/AggregateEndpointComponent.ts
  src/queryExecutionContext/EndpointComponent/TopEndpointComponent.ts
  src/queryExecutionContext/defaultQueryExecutionContext.ts
  src/queryExecutionContext/headerUtils.ts
  src/queryIterator.ts
  src/queryMetrics/clientSideMetrics.ts
  src/request/Response.ts
  test/integration/crossPartition.spec.ts
Labels: v3

#292 Add scripts to OM
  src/client/Container/Container.ts
  src/client/Script/Scripts.ts
  test/common/PrivateContainer.ts
  test/common/TestHelpers.ts
  test/functional/sproc.spec.ts
  test/functional/trigger.spec.ts
  test/functional/udf.spec.ts
Labels: breaking, v3

#295 [V3] Switch _ts type from string to number (#252)
  src/client/Resource.ts
Labels: v3

#294 Switch to node-abort-controller
  package-lock.json
  package.json
  src/request/RequestHandler.ts
Labels: v3

#291 Remove type overloads in ClientContext
  src/ClientContext.ts
Labels: v3

#297 Plugin implementation
  src/ClientContext.ts
  src/CosmosClientOptions.ts
  src/index.ts
  src/plugins/Plugin.ts
  src/request/RequestContext.ts
  src/request/RequestHandler.ts
  test/functional/plugin.spec.ts
Labels: feature, v3

#293 Add activityId to response and custom executeRequest
  src/request/FeedResponse.ts
  test/integration/query.spec.ts
Labels: v3

#305 Remove semaphore from PartitionKeyRangeCache
  src/routing/partitionKeyRangeCache.ts
Labels: v3
