Repository Azure/azure-cosmos-js, pull requests merged in 2019-03, with the labels that each got.

#245 Replace request internals with fetch
  package-lock.json
  package.json
  src/ClientContext.ts
  src/LocationCache.ts
  src/client/Conflict/ConflictDefinition.ts
  src/common/constants.ts
  src/common/helper.ts
  src/globalEndpointManager.ts
  src/queryExecutionContext/EndpointComponent/AggregateEndpointComponent.ts
  src/queryExecutionContext/EndpointComponent/IEndpointComponent.ts
  src/queryExecutionContext/EndpointComponent/OrderByEndpointComponent.ts
  src/queryExecutionContext/EndpointComponent/TopEndpointComponent.ts
  src/queryExecutionContext/IExecutionContext.ts
  src/queryExecutionContext/documentProducer.ts
  src/queryExecutionContext/parallelQueryExecutionContextBase.ts
  src/queryExecutionContext/pipelinedQueryExecutionContext.ts
  src/queryExecutionContext/proxyQueryExecutionContext.ts
  src/request/RequestContext.ts
  src/request/RequestHandler.ts
  src/request/TimeoutError.ts
  src/request/request.ts
  src/retry/RetryPolicy.ts
  src/retry/defaultRetryPolicy.ts
  src/retry/endpointDiscoveryRetryPolicy.ts
  src/retry/resourceThrottleRetryPolicy.ts
  src/retry/retryUtility.ts
  src/retry/sessionRetryPolicy.ts
  src/session/SessionContext.ts
  src/session/sessionContainer.ts
  src/test/functional/client.spec.ts
  src/test/integration/crossPartition.spec.ts
  src/test/integration/session.spec.ts
  src/test/unit/locationCache.spec.ts
  src/test/unit/sessionContainer.spec.ts
Labels: v3

#246 Refactor ConnectionPolicy and RetryOptions to interface
  package.json
  src/ClientContext.ts
  src/CosmosClient.ts
  src/CosmosClientOptions.ts
  src/LocationCache.ts
  src/common/helper.ts
  src/documents/ConnectionPolicy.ts
  src/documents/MediaReadMode.ts
  src/documents/index.ts
  src/globalEndpointManager.ts
  src/index.ts
  src/request/RequestHandler.ts
  src/retry/retryOptions.ts
  src/retry/retryUtility.ts
  src/retry/sessionRetryPolicy.ts
  src/test/functional/client.spec.ts
  src/test/integration/multiregion.spec.ts
  src/test/integration/retry.spec.ts
  src/test/integration/sslVerification.spec.ts
  src/test/unit/locationCache.spec.ts
Labels: v3

#264 Fix ChangeFeed hasMoreResults
  src/ChangeFeedIterator.ts
  src/ClientContext.ts
  src/retry/retryUtility.ts
  src/test/integration/incrementalFeed.spec.ts
Labels: bug, needs-v3-port

#262 Remove MediaOptions
  src/index.ts
  src/request/MediaOptions.ts
  src/request/index.ts
  src/request/request.ts
Labels: v3

#259 Regional failover should work within retry policy
  src/retry/retryUtility.ts
Labels: bug, needs-v3-port

#266 Port ChangeFeed fix #244
  src/ChangeFeedIterator.ts
  src/ClientContext.ts
  src/retry/retryUtility.ts
  src/test/integration/incrementalFeed.spec.ts
Labels: bug

#267 port #257
  src/retry/retryUtility.ts
Labels: bug
